//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.13 at 01:07:30 AM PST 
//


package de.unitrier.dblp;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.google.common.base.Function;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "author")
@Entity
@NamedQueries({
	@NamedQuery(name="Author.byName", query="SELECT a FROM Author a WHERE a.content=:name"),
	@NamedQuery(name="Author.byNamePrefix", query="SELECT a FROM Author a WHERE a.content LIKE :namePrefix || '%'"),
})
public class Author implements Serializable {
	private static final long serialVersionUID = 8576304880996464574L;
	
	@XmlValue
    @Id
    @Column(name="AUTHOR_NAME", nullable=false)
    protected String content;

    public Author() {	}
    
    public Author(String name) {
		this.content = name;
	}
    
    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }
    
    @Override
    public boolean equals(Object obj) {
    	if (obj instanceof Author == false) {
			return false;
		}
		if (this == obj) {
			return true;
		}
		Author rhs = (Author) obj;
		return new EqualsBuilder()
					.append(content, rhs.content)
					.isEquals();
    }
    
    @Override
    public int hashCode() {
    	return new HashCodeBuilder(17, 37)
        			.append(content)
        			.toHashCode();
    }
    
    @Override
    public String toString() {
    	return new ToStringBuilder(this, ToStringStyle.SHORT_PREFIX_STYLE).
    					append("AuthorName", this.content).toString();
    }
    
    public static final Function<Author, String> FN_AUTHOR_NAME = new Function<Author, String>() {
    	@Override
    	public String apply(Author author) {
    		return author.getContent();
    	}
    };
}
