DELETE FROM dbsa_sbj
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('1','Theoretical computer science');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('2','Automata theory');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('3','Automata theory');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('4','Number theory');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('5','Graph theory');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('6','Type theory');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('7','Category theory');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('8','Computational geometry');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('9','Quantum computing theory');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('10','Algorithms and data structures');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('11','Analysis of algorithms');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('12','Algorithms');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('13','Data structures');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('14','Computer elements and architecture');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('15','Digital logic');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('16','Microarchitecture');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('17','Multiprocessing');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('18','Computational science');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('19','Numerical analysis');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('20','Computational physics');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('21','Computational chemistry');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('22','Bioinformatics');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('23','Artificial Intelligence');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('24','Machine learning');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('25','Computer vision');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('26','Natural language processing/Computational linguistics');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('27','Robotics');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('28','Image Processing');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('29','Pattern Recognition');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('30','Congnitive science');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('31','Evolutionary computation');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('32','Information retrieval');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('33','Knowledge Representation');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('34','Software Engineering');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('35','Operating systems');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('36','Computer networks');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('37','Databases');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('38','Computer security');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('39','Ubiquitous computing');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('40','Systems architecture');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('41','Compiler design');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('42','Programming languages');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('43','Other');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('44','Data mining');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('45','Information Retrieval');
INSERT INTO `dbsa_sbj` (`id`, `sbj_name`) VALUES('46','Information Extraction');
