//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.10 at 11:38:48 PM PST 
//


package org.acm.taxonomy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for nodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="isRelatedTo" type="{}isRelatedToType" minOccurs="0"/>
 *         &lt;element name="hasNote" type="{}hasNoteType" minOccurs="0"/>
 *         &lt;element name="isComposedBy" type="{}isComposedByType" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nodeType", propOrder = {
    "isRelatedTo",
    "hasNote",
    "isComposedBy"
})
public class NodeType {

    protected IsRelatedToType isRelatedTo;
    protected HasNoteType hasNote;
    protected IsComposedByType isComposedBy;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute
    protected String label;

    /**
     * Gets the value of the isRelatedTo property.
     * 
     * @return
     *     possible object is
     *     {@link IsRelatedToType }
     *     
     */
    public IsRelatedToType getIsRelatedTo() {
        return isRelatedTo;
    }

    /**
     * Sets the value of the isRelatedTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsRelatedToType }
     *     
     */
    public void setIsRelatedTo(IsRelatedToType value) {
        this.isRelatedTo = value;
    }

    /**
     * Gets the value of the hasNote property.
     * 
     * @return
     *     possible object is
     *     {@link HasNoteType }
     *     
     */
    public HasNoteType getHasNote() {
        return hasNote;
    }

    /**
     * Sets the value of the hasNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link HasNoteType }
     *     
     */
    public void setHasNote(HasNoteType value) {
        this.hasNote = value;
    }

    /**
     * Gets the value of the isComposedBy property.
     * 
     * @return
     *     possible object is
     *     {@link IsComposedByType }
     *     
     */
    public IsComposedByType getIsComposedBy() {
        return isComposedBy;
    }

    /**
     * Sets the value of the isComposedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsComposedByType }
     *     
     */
    public void setIsComposedBy(IsComposedByType value) {
        this.isComposedBy = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

}
